remote_theme: pages-themes/minimal@v0.2.0
#theme: jekyll-theme-minimal
title: "Dr. Lin Htet Naing"
description: "Machine Learning & Health Data Science Projects"
logo: /assets/profile.jpg    # optional
show_downloads: false
